/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreneauxRouteImport } from './routes/creneaux'
import { Route as SaisieTerrainRouteImport } from './routes/saisie-terrain'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreneauxRoute = CreneauxRouteImport.update({
  id: '/creneaux',
  path: '/creneaux',
  getParentRoute: () => rootRouteImport,
} as any)
const SaisieTerrainRoute = SaisieTerrainRouteImport.update({
  id: '/saisie-terrain',
  path: '/saisie-terrain',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creneaux': typeof CreneauxRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creneaux': typeof CreneauxRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creneaux': typeof CreneauxRoute
  '/saisie-terrain': typeof SaisieTerrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/creneaux' | '/saisie-terrain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/creneaux' | '/saisie-terrain'
  id: '__root__' | '/' | '/contact' | '/creneaux' | '/saisie-terrain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreneauxRoute: typeof CreneauxRoute
  SaisieTerrainRoute: typeof SaisieTerrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creneaux': {
      id: '/creneaux'
      path: '/creneaux'
      fullPath: '/creneaux'
      preLoaderRoute: typeof CreneauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saisie-terrain': {
      id: '/saisie-terrain'
      path: '/saisie-terrain'
      fullPath: '/saisie-terrain'
      preLoaderRoute: typeof SaisieTerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreneauxRoute: CreneauxRoute,
  SaisieTerrainRoute: SaisieTerrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
